absolute_urls: false
timezone: 'Europe/Paris'

home:
  alias: '/blog'

pages:
  theme: notepad
  markdown_extra: true
  process:
    markdown: true
    twig: false
  expires: 604800

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'
  lifetime: 604800
  gzip: true

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: false
  css_rewrite: false
  js_pipeline: false
  js_minify: false
  collections:
    jquery: https://cdn.jsdelivr.net/jquery/2.1.4/jquery.min.js
    externaljs:
      - https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/js/foundation.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/fastclick/1.0.6/fastclick.min.js
      - https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js
      - https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js
    externalcss:
      - https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/normalize.min.css
      - https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/foundation.min.css
      - https://cdn.jsdelivr.net/animatecss/3.5.0/animate.min.css
      - https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css
      - https://cdn.jsdelivr.net/g/jquery.slick@1.5.9(slick.css+slick-theme.css)
    fonts:
      - https://fonts.googleapis.com/css?family=Montserrat:400,700&amp;subset=latin,latin-ext
      - https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800,600&amp;subset=latin,latin-ext

errors:
  display: false
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
